SELECT name AS TableName
FROM sys.tables;

CREATE TABLE EMPP(
ID INT,
NAME VARCHAR(50)
);

INSERT INTO EMP (ID, NAME) VALUES (1, 'SOURAV');
INSERT INTO EMP (ID, NAME) VALUES (2, 'RAHUL');

SELECT * FROM Emp;

CREATE DATABASE EMPLOYEE1;
-- DROP DATABASE EMPLOYEE1;